import './global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <header></header>
        <div className= "centered-div">
          {children}
        </div>
        <footer></footer>
      </body>
    </html>
  )
}
